### ISSUE TITLE
Dependency on the pycrypto package

### ISSUE THREAD

**Issue by arithmetric** [pantheon-systems/kibana_utils#18]
Using Python 2.7 bundled with MacOS 10.11, I encountered the `ImportError: No module named Crypto` error when running commands.

For example:

```
$ fab -f fabfile.py -l
Traceback (most recent call last):
  File "/usr/local/bin/fab", line 7, in <module>
    from fabric.main import main
  File "/usr/local/lib/python2.7/site-packages/fabric/main.py", line 19, in <module>
    from fabric import api, state, colors
  File "/usr/local/lib/python2.7/site-packages/fabric/api.py", line 11, in <module>
    from fabric.decorators import (hosts, roles, runs_once, with_settings, task,
  File "/usr/local/lib/python2.7/site-packages/fabric/decorators.py", line 9, in <module>
    from Crypto import Random
ImportError: No module named Crypto
```

There seems to be a dependency on the Crypto package that is not included in the requirements files.

I was able to resolve this issue by adding `pycrypto==2.6.1` to `requirements/common.txt` and running `pip install -r requirements.txt` again.

**Comment by nstielau** [comment]
Thanks!  Resolved.  

I have no idea if this works with the newer Kibana... Let me know ;)
